# Generated by Django 2.2.16 on 2023-03-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20230309_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': ('Пост',), 'verbose_name_plural': 'Посты'},
        ),
    ]
