# Generated by Django 2.2.16 on 2023-03-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20230309_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Пост',), 'verbose_name_plural': 'Посты'},
        ),
    ]
