# Generated by Django 2.2.16 on 2023-03-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20230309_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'ordering': ('-pub_date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ('-pub_date',), 'verbose_name': ('Пост',), 'verbose_name_plural': 'Посты'},
        ),
    ]
